apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: webinar-demo
  name: webinar-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      run: webinar-demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: webinar-demo
    spec:
      containers:
      - image: nj93/webinar-demo:v1
        name: webinar-demo
        volumeMounts:
        - name: config-mount
          mountPath: /app/config/config.json
          subPath: config.json
        ports:
        - containerPort: 8080
        resources:
         requests:
           cpu: 200m
      volumes:
      - name: config-mount
        configMap:
          name: config-json
        
status: {}
