apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: webinar-demo
  name: webinar-demo
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: webinar-demo
  type: LoadBalancer
status:
  loadBalancer: {}
